// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8X_Il3ItSA4n8eFW1yx24W5w0dmS2lvM',
    appId: '1:394385627070:web:58fe3922e2c8ae2b37cbef',
    messagingSenderId: '394385627070',
    projectId: 'vonana-5e86c',
    authDomain: 'vonana-5e86c.firebaseapp.com',
    storageBucket: 'vonana-5e86c.firebasestorage.app',
    measurementId: 'G-Y00XERP0GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxT_khKR_lyLt714h-IwllrtdI5GHkGko',
    appId: '1:394385627070:android:6a58ceac910bbaa637cbef',
    messagingSenderId: '394385627070',
    projectId: 'vonana-5e86c',
    storageBucket: 'vonana-5e86c.firebasestorage.app',
  );
}
